### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by mk-pmb** [mattbierner/fifty-shades-of-dyspepsia#1]
Hi! I'd have loved to try your project in my attempt to learn `apep`, but one of the deps seems very broken:

```text
$ git clone …
$ npm install
fifty-shades-of-dyspepsia@0.0.0 /…/fifty-shades-of-dyspepsia
├─┬ apep@1.3.1
│ └── walker-sample@0.0.0
├─┬ apep-md@0.0.1
│ └── apep-std-sep@0.0.2
├── apep-std-transformations@0.1.0
└── apep-std-vars@0.0.0

$ nodejs index.js
/…/fifty-shades-of-dyspepsia/node_modules/walker-sample/index.js:16
}());
 ^
SyntaxError: Unexpected token (

$ node-versions
Node.js v6.8.1, npm v3.10.8, Ubuntu 14.04.5 LTS trusty
```

Maybe there are some steps missing in the install instructions?

**Comment by mattbierner** [comment]
Thank you for reporting this. I've published an update to `walker-sample` that fixes it for newer versions of node, and picked up this change up in Apep `1.3.2`. Just bump the version number and you should be good to go. Please let me know if you run into any other issues.
